### ISSUE TITLE
[PR] Support transforming of latest CSS @import syntax

### ISSUE THREAD

**Issue by fuweichin** [markwylde/css-bun#2]
## Background

Latest CSS [@import syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#syntax) contains 3 options: `layer(layer-name) `, `supports(condition-text)` and `media-condition-list`.

All major browsers (except iOS Safari) support the `@import` syntax.

Some web developers want to try/use this feature, so they need toolchain update.

## Basic Idea

1. transform each option of `@import` to corresponding at-rule, and wrap the imported content with those at-rules. 

+ e.g. transform `layer(layer-name)` to `@layer layer-name { ... } `
+ transform `supports(condition-text)` to `@supports (condition-text) { ... }`
+ transform `media-condition-list` to `@media media-condition-list { ... } `

2. If a CSSImportRule contains two or more of `layerName`, `supportsText`, `media`, then nest the output at-rules in order.
   e.g. nesting order of at-rules (from outer to inner) can be `@media`, `@supports`, `@layer`

## Reference Implementation

<details>
<summary>index.mjs</summary>

```js
import path from 'node:path';
import fs from 'node:fs';
import resolve from 'resolve';

export default function cssbun(entryFile) {
  let fileName = './' + path.basename(entryFile);
  let referrer = path.resolve(entryFile);
  return grabFile(fileName, referrer, [], []);
}

function grabFile(fileName, referrer, alreadyIncluded, stack) {
  let filePath;
  let baseDir = path.dirname(referrer);
  if (fileName.startsWith('./') || fileName.startsWith('../')) {
    filePath = path.resolve(baseDir, fileName);
  } else {
    filePath = resolve.sync(fileName, {includeCoreModules: false, basedir: baseDir});
  }
  if (stack.includes(filePath)) {
    console.warn('Resursive import detected: ' + fileName);
    return '';
  }
  if (alreadyIncluded.includes(filePath)) {
    console.warn('Duplicated import detected: ' + fileName);
    return '';
  }
  stack.push(filePath);
  alreadyIncluded.push(filePath);
  let content = fs.readFileSync(filePath, {encoding: 'utf-8'});
  return content.replace(/^@import\s+"([^"]+)"(?:[^;]+)?;/mg, (atRuleCssText, href) => {
    let rule = parseImportRule(atRuleCssText);
    if (rule === null || /^(https?|data):/.test(href)) // unexpected @import syntax or @import url
      return atRuleCssText;
    let stackLevel = stack.length;
    let depContent = grabFile(href, filePath, alreadyIncluded, stack);
    if (stack.length > stackLevel) {
      stack.pop();
    }
    let {media, supportsText, layerName} = rule;
    if ((media || supportsText || layerName) && depContent) {
      return wrapWithAtRule(depContent, rule);
    }
    return depContent;
  });
}

function wrapWithAtRule(cssText, cssImportRule) {
  let content = '';
  let stack = [];

  let {media, supportsText, layerName} = cssImportRule;
  if (media) {
    content += `@media ${media} {\n`;
    stack.push('}\n');
  }
  if (supportsText) {
    content += `@supports (${supportsText}) {\n`;
    stack.push('}\n');
  }
  if (layerName) {
    content += `@layer ${layerName} {\n`;
    stack.push('}\n');
  }
  content += cssText;
  while (stack.length > 0) {
    content += stack.pop();
  }
  return content;
}

function parseImportRule(str) {
  let href = '';
  let media = null;
  let supportsText = null;
  let layerName = null;

  let len = str.length;
  let cur = 0;
  let m = str.match(/@import "([^"]+)"/);
  if (m) {
    href = m[1];
    cur = m[0].length;
    for (let i = cur; i < len; i++) {
      if (str.charCodeAt(i) === 32) cur += 1;
      else break;
    }
  } else {
    return null;
  }
  if (str.startsWith('layer(', cur)) { // seek layerName
    str.slice(cur).replace(/^layer\(([\w-]+(?:\.[\w-]+)*)\)/, ($0, $1) => {
      layerName = $1;
      cur += $0.length;
      for (let i = cur; i < len; i++) {
        if (str.charCodeAt(i) === 32) cur += 1;
        else break;
      }
    });
  }

  if (str.startsWith('supports(', cur)) { // seek supportsText
    let end = seekParenthesesToEnd(str, cur, []);
    if (end !== -1) {
      supportsText = str.slice(cur + 9, end - 1);
      cur = end;
      for (let i = cur; i < len; i++) {
        if (str.charCodeAt(i) === 32) cur += 1;
        else break;
      }
    }
  }

  if (!str.startsWith(';')) { // seek media list
    let end = cur;
    for (let i = cur; i < len; i++) {
      if (str.charCodeAt(i) !== 59) end += 1;
    }
    if (end > cur) {
      media = str.slice(cur, end);
    }
  }

  return {href, media, supportsText, layerName};
}

let seekParenthesesToEnd = (s, offset, stack) => {
  let i = offset;
  for (let c; i < s.length; i++) {
    c = s.charAt(i);
    switch (c) {
      case '(':
        stack.push(c);
        break;
      case ')':
        if (stack.pop() !== '(') {
          throw new Error('Unexpected token ) at ' + i);
        }
        if (stack.length === 0) {
          return i + 1;
        }
        break;
    }
  }
  return -1;
};
```
</details>

## Unit Test

`cssbun -o index.bundle.css index.css`

### input

<details open="">
<summary>index.css</summary>

```css
@layer reset,self;

@import "./reset.css" layer(reset);
@import "./utils.css";
@import "./index-p3.css" supports(color: color(display-p3 1 0 0)) (color-gamut: p3);
@import "./index-dark.css" (prefers-color-scheme: dark);

@layer self {
  fieldset {
    border-radius: 2px;
  }
}
```
</details>

<details>
<summary>reset.css</summary>

```css
input[type="number"] {
  -webkit-appearance: textfield;
  appearance: textfield;
}
input[type="number"]::-webkit-inner-spin-button {
  display: none;
}
```
</details>

<details>
<summary>utils.css</summary>

```css
.box {
  border-color: #ff0000;
}
```
</details>

<details>
<summary>index-p3.css</summary>

```css
.box {
  border-color: color(display-p3 1 0 0);
}
```
</details>

<details>
<summary>index-dark.css</summary>

```css
body {
  background-color: #121212;
}
```
</details>

### output

<details open="">
<summary>index.bundle.css</summary>

```css
@layer reset, self;

@layer(reset) {
input[type="number"] {
  -webkit-appearance: textfield;
  appearance: textfield;
}
input[type="number"]::-webkit-inner-spin-button {
  display: none;
}
}

.box {
  border-color: #ff0000;
}

@media (color-gamut: p3) {
@supports (color: color(display-p3 1 0 0)) {
.box {
  border-color: color(display-p3 1 0 0);
}
}
}

@media (prefers-color-scheme: dark) {
body {
  background-color: #121212;
}
}

@layer self {
  fieldset {
    border-radius: 2px;
  }
}
```
</details>
